package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, December 18, 2014 9:44:36 PM PST
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
  	 * The value representing REQUEST_PROCESSING_POLICY_ID.
  	 */
  public static final int value = (int)(22L);
}
