package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, December 18, 2014 9:44:37 PM PST
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
     */
  public static final short value = (short)(2);
}
